import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { CounterStoreProvider } from '@/providers/counter-store-provider';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable,
        )}
      >
        <CounterStoreProvider>{children}</CounterStoreProvider>
      </body>
    </html>
  );
}
